# These are supported funding model platforms

github: #ETCorps.
#Extraterestrial-Corporations.
#ETCK333-tb9ir60.
#Master333-ui-web.
patreon: # Chais Fitzwater.
open_collective: # ETC.
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # https://www.github.com/ *ETCorps-BMO-Account-186-International.bankbridge/ *capitol-markets.yaml/ *open.sql
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
